### ISSUE TITLE
parsing error in https://tokei.rs/b1/github

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [XAMPPRocky/tokei_rs#1]
https://github.com/Aaronepower/tokei/issues/154

probably some parsing error (dot in the repo name):

this repo comes back with 403:
https://tokei.rs/b1/github/random-archer/nspawn.sh

while this repository (same account) works fine:
https://tokei.rs/b1/github/random-archer/dovecot_plugin_syncer

**Comment by XAMPPRocky** [comment]
thank you for your issue! It seems this has been fixed. As `nspawn.sh` now returns ![](https://tokei.rs/b1/github/random-archer/nspawn.sh)

**Comment by Andrei-Pozolotin** [comment]
thank you
