### ISSUE TITLE
Add libre license

### ISSUE THREAD

**Issue by throwaway1037** [XAMPPRocky/tokei_rs#103]
Until a libre license is added, this project is technically proprietary, as it is covered by copyright law.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I intend to resolve this issue soon, but you can assume it's MIT / APACHE 2.0.

**Comment by throwaway1037** [comment]
I presume your intentions are good, although it would be foolish to assume a license, because you could end up being liable for copyright infringement.

**Comment by throwaway1037** [comment]
(Just giving this thread a bump.)

**Comment by elliotwutingfeng** [comment]
Thanks! I think this can be closed now.
