### ISSUE TITLE
Count is the same for all categories

### ISSUE THREAD

**Issue by scurest** [XAMPPRocky/tokei_rs#12]
The badge seems to count total lines regardless of the `?category=` values.

![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=blanks)  
![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=code)  
![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=files)  
![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=lines)  
![](https://tokei.rs/b1/github/XAMPPRocky/tokei?category=comments)  

All give 6.9K for me.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've fixed this in master and have deployed this to production.
