### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by Rapiz1** [XAMPPRocky/tokei_rs#14]
https://tokei.rs/

**Comment by XAMPPRocky** [comment]
Hello, thank you for this issue! I am aware of the issue as I'm currently performing maintenance on the site. I hope to have it back up by the end of the day.

**Comment by Rapiz1** [comment]
Got it :)

**Comment by XAMPPRocky** [comment]
I'm going to leave this issue open until it's back up to avoid duplicate issues.

**Comment by XAMPPRocky** [comment]
Tokei.rs is back online.
