### ISSUE TITLE
Feature request: Allow chosing a branch

### ISSUE THREAD

**Issue by TheAlexDev23** [XAMPPRocky/tokei_rs#211]
The ability to chose a branch of the repo other than the main one

**Comment by elliotwutingfeng** [comment]
Would a syntax like `https://tokei.rs/b1/github/XAMPPRocky/tokei_rs@branch_name` be suitable? `@branch_name` would be optional.

**Comment by XAMPPRocky** [comment]
Thank you for your issue!  Is `@` the conventional syntax for addressing a specific branch? If it is then it seems fine, otherwise I'd prefer a query parameter.

**Comment by elliotwutingfeng** [comment]
I don't think it is conventional in git, but I've seen `@` being used for `pip install`. I think query parameter is better actually.
