### ISSUE TITLE
Caching statement appears to have no effect

### ISSUE THREAD

**Issue by elliotwutingfeng** [XAMPPRocky/tokei_rs#213]
https://github.com/XAMPPRocky/tokei_rs/blob/051b944e7a363ee8de2ad3a988d117065cf7a013/src/main.rs#L140-L156

`found_match` is always false.

- However, requests for the same SHA are still cached as per normal even if the above portion is removed (no redundant git clone).
- Because `found_match` is always false, server returns cached results but with response code `200 OK` instead of `304 Not Modified`

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Why is it always false? It seems like it should only be false if the nothing in header weak_eq's a current SHA.

**Comment by elliotwutingfeng** [comment]
I rolled back to 8840c6b9c7a0dd5f2a12c652782190ac73e90743 and observed the same behavior; `if_none_match`  remains empty even after repeated requests and the caching still works fine after commenting out the `if` block.

**Comment by elliotwutingfeng** [comment]
Thanks! That clears things up, I didn't know about that header. Just fixed a bug in #212 where the wrong etag was passed to response.
