### ISSUE TITLE
Does the service work?

### ISSUE THREAD

**Issue by nickcox** [XAMPPRocky/tokei_rs#27]
I've tried the example URL (https://tokei.rs/b1/github/XAMPPRocky/tokei_rs) from a couple of different ISPs but always get an error like:

```
Error 502 Ray ID: 542bb9b6bc1fd932 • 2019-12-10 02:17:57 UTC
Bad gateway
```

**Comment by XAMPPRocky** [comment]
Hello, yes sorry there was internal service error and should be back up now.

**Comment by ZanderBrown** [comment]
Still dead here

**Comment by XAMPPRocky** [comment]
@ZanderBrown Back up.
