### ISSUE TITLE
tokei.rs badge is currently returning 500 Internal Server Error

### ISSUE THREAD

**Issue by huxi** [XAMPPRocky/tokei_rs#32]
Examples:
https://tokei.rs/b1/github/huxi/rusty_ulid

[![tokei](https://tokei.rs/b1/github/huxi/rusty_ulid)](https://github.com/XAMPPRocky/tokei)

https://tokei.rs is failing with 502 Bad Gateway

**Comment by XAMPPRocky** [comment]
Thank you for your issue! this is fixed now.
