### ISSUE TITLE
Feature request: support by-language breakdown

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [XAMPPRocky/tokei_rs#4]
1. currently, only total stats are available via `?category=`
https://tokei.rs/b1/github/org/repo?category=lines

2. this request is to support by-language breakdown via `?language=`
https://tokei.rs/b1/github/org/repo?language=java,scala

to render badge with:
```
Java:N1 Scala:N2
```

**Comment by elliotwutingfeng** [comment]
This appears to be the same as #6, even though this issue is older.
