### ISSUE TITLE
Feature request: custom host URL

### ISSUE THREAD

**Issue by sci4me** [XAMPPRocky/tokei_rs#5]
I would like to be able to use tokei.rs on my own Gitea server. Instead of `tokei.rs/b1/{github|gitlab}/user/repo` it could be `tokei.rs/b1/url/user/repo`.

EDIT: After browsing the source code, I see that this is kind of already possible, for `.com` domains. If we just removed the `.com`, anyone could use the service with any git host.

**Comment by JHaig343** [comment]
I could help out with this one if it still needs work @XAMPPRocky

**Comment by XAMPPRocky** [comment]
@JHaig343 Hello, sorry I only just saw this. I've just now released a new version that will support any host for the url.

**Comment by JHaig343** [comment]
No problem, thanks for the update!

**Comment by nektro** [comment]
has the new version been pushed to https://tokei.rs/ ? because I'm trying to use this with a gitea instance and the badge says `Incorrect URL`.

**Comment by XAMPPRocky** [comment]
@nektro Yes, can you show the URL you're trying to use?

**Comment by nektro** [comment]
`https://tokei.rs/b1/gitea_instance_host/user/repo`

**Comment by XAMPPRocky** [comment]
@nektro That repository is not publicly accessible, it needs to be public in order for tokei to read the repository.

**Comment by nektro** [comment]
ah sorry about that, didn't realize it was public
