### ISSUE TITLE
Github badge failing for c++ repo

### ISSUE THREAD

**Issue by awinkler** [XAMPPRocky/tokei_rs#50]
Hi! Thanks for this useful library! Since a few weeks this C++ repo is not being counted any more, any suggestions? Seems like it's related to the repo, as others still work.

![](https://tokei.rs/b1/github/ethz-adrl/towr?category=code)
`![](https://tokei.rs/b1/github/ethz-adrl/towr?category=code)`

**Comment by XAMPPRocky** [comment]
Thank you for issue! I've pushed a fix for this to master and will try to push out a deploy soon.
