### ISSUE TITLE
Badges: add filter ?type=Markdown,Rust

### ISSUE THREAD

**Issue by jmfayard** [XAMPPRocky/tokei_rs#6]
Hello, 
The badge does not really work for me. 
Here is what it shows for my repo
![](https://tokei.rs/b1/github/jmfayard/gradle-kotlin-dsl-libs?type=kotlin)

Actually, my real LoC is 1k, because what is relevant in my case is the output of `-t=Kotlin`

The rest is not really part of my codebase. 

```
$ tokei
--------------------------------------------------------------------------
 Language       Files        Lines         Code     Comments       Blanks
--------------------------------------------------------------------------
 Batch              1           84           61            0           23
 JSON              27        14287        14287            0            0
 Kotlin            18          957          668           61          228
 Markdown           4          178          178            0            0
 Shell              1          172          128           23           21
 Plain Text        53         2465         2465            0            0
--------------------------------------------------------------------------
 Total            104        18143        17787           84          272
--------------------------------------------------------------------------
```

I would like to have in the badge URL the same option that in the command line

```
$ tokei --help
    -t, --type <types>            Filters output by language type, seperated by a comma. i.e. -t=Rust,Markdown
```

**Comment by JoeHowarth** [comment]
I too would like this feature 👍

**Comment by HoLLy-HaCKeR** [comment]
I have a similar scenario where I have a bunch of json files that massively bloat my linecount, and I also have some autogenerated source files I would like to exclude.

**Comment by kevinmichaelchen** [comment]
@HoLLy-HaCKeR see [this comment](https://github.com/XAMPPRocky/tokei_rs/issues/111#issuecomment-889804537).

You could create an `.ignore` file:
```
*.json
```

**Comment by XAMPPRocky** [comment]
I'll also note you can also use `.tokeignore` if you just want it to apply to tokei as `.ignore` is a bit more general.
