### ISSUE TITLE
Code by type

### ISSUE THREAD

**Issue by cinemast** [XAMPPRocky/tokei_rs#61]
Thank you for providing this awesome service.

Do you think it would be possible to differ the size for the following categories:
- functionality (the actual code providing the functionality)
- test (code containting tests)
- doc (code/files containting documentation and maybge also example code).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However this feature is not currently possible with Tokei. To understand that you would need a language specific parser that understands what parts of code are documentation, tests, etc. Which is not something I plan to add to tokei.
