### ISSUE TITLE
Badge stuck on "processing..."

### ISSUE THREAD

**Issue by MonliH** [XAMPPRocky/tokei_rs#79]
When I navigate to [`https://tokei.rs/b1/github/fluo-lang/fluoc`](https://tokei.rs/b1/github/fluo-lang/fluoc), the badge gets stuck "processing". It looks like this:
<img width="131" alt="Screen Shot 2020-11-21 at 8 33 50 PM" src="https://user-images.githubusercontent.com/30177086/99891533-dea3ce80-2c38-11eb-8dc5-7f2c9c4b347e.png">

It seems to be a problem specifically with that repo (`fluo-lang/fluo`). In my testing, it seems to be a problem with this server-side code, because running `tokei` locally works.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! It seems to be fixed now.

**Comment by MonliH** [comment]
Oh, awesome, thanks!
