### ISSUE TITLE
Primary language badge

### ISSUE THREAD

**Issue by spenserblack** [XAMPPRocky/tokei_rs#87]
I think it would be nice to have a badge for the language with the most lines (probably by LoC)? It could look something like this: ![Primary Language Badge](https://img.shields.io/badge/primary%20language-rust-blue)

It would be cool if each language had its own color, but to get the feature started it might be best if all languages used the same color (blue) as the other badges.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That is interesting. I don't know if I would implement each language having its own colour, as if I was to do that, I would want it to be done in a way that wouldn't require hard coding language to colour, and that would probably doing something like generatinng a random hexcode, but that has the potential for ugly colour combinations. Maybe I'll just also let you override the colour.

**Comment by spenserblack** [comment]
I could make a PR if you want :smile:

**Comment by XAMPPRocky** [comment]
Feel free if you want to.

**Comment by miraclx** [comment]
> Thank you for your issue! That is interesting. I don't know if I would implement each language having its own colour, as if I was to do that, I would want it to be done in a way that wouldn't require hard coding language to colour, and that would probably doing something like generatinng a random hexcode, but that has the potential for ugly colour combinations. Maybe I'll just also let you override the colour.

Actually, you wouldn't need to hardcode the color associations, GitHub's got your back

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by spenserblack** [comment]
:thinking: I'm failing to compile this on nightly. I tried following rocket's recommendation of making sure both rustc and dependencies are up to date with `rustup update && cargo update`, but that introduces different compilation errors currently in the serde sub-dependency. Is there a recommended rustc version to use to compile this?

***

@miraclx That's a cool idea! However, tokei supports some languages that linguist (currently) does not, like Emojicode and Elvish. So at least *some* color associations would need to be defined, or a default value used where not defined.

**Comment by XAMPPRocky** [comment]
@spenserblack Admiteddly I haven't had a need to compile and run in a long time, so it might require some updates of dependencies/code to compile.

**Comment by miraclx** [comment]
@spenserblack, we could generate language-color key-value pairs extended from linguist's yml file and only add modifications to that for extra languages.

Or maybe even two files, one that's automatically generated and the other that's handcoded. Users can then make PRs to add colors for whatever language they want (if not already present).

The auto-generated file could be generated in a build script so it only runs once. Or maybe a shell script for the Docker image.

Or maybe as part of the server so for long running uses of the server, at certain intervals it could check GitHub for changes to linguist's yml or the self-contained color bindings in this repo and update itself.

**Comment by spenserblack** [comment]
@XAMPPRocky Got it to compile by downgrading to `rustc 1.44.0-nightly (537ccdf3a 2020-04-02)`. I'm not sure if earlier or later versions will compile, but perhaps that should be documented somewhere for contributors?

***

@miraclx I think that's a cool idea, but I think the first step is to simply implement a badge for the primary language without any per-language coloring. In my opinion, I think a primary language badge is its own feature, and then adding color is a new feature built on top of that. So, presently, I think it's best if I made a PR that used the same blue color that all the other badges use, and then the discussion on coloring the language badge can be in a separate issue. @XAMPPRocky, do you have a preference?

**Comment by XAMPPRocky** [comment]
>  I'm not sure if earlier or later versions will compile, but perhaps that should be documented somewhere for contributors?

For what it's worth, I would prefer to just upgrade whatever's needed to get this to compile on the latest nightly.

> @miraclx I think that's a cool idea, but I think the first step is to simply implement a badge for the primary language without any per-language coloring. In my opinion, I think a primary language badge is its own feature, and then adding color is a new feature built on top of that. So, presently, I think it's best if I made a PR that used the same blue color that all the other badges use, and then the discussion on coloring the language badge can be in a separate issue. @XAMPPRocky, do you have a preference?

That makes sense to me. There's no reason the colours can't be added after the this, and I would still like to explore adding a cooler override parameter.

**Comment by miraclx** [comment]
Yeah, sounds good to me.

And the override parameter is also a nice to have.
